export const festivalDays = [
  {
    id: "jour-1",
    label: { fr: "Premier jour : 26 juin", ar: "اليوم الأول: 26 يونيو" },
    shortDate: { fr: "26 juin", ar: "26 يونيو" },
    events: {
      fr: [
        {
          time: "16h00",
          title: "Vernissage de l'exposition d'arts plastiques",
          subtitle: null,
          moderator: {
            label: "Présentation",
            text: "**Fatima Zahra Sghier** et **Dalida BenSafaj**",
          },
          sectionLabel: "Artistes exposantes :",
          participants: [
            "Amina Rizki / Rim Laâbi",
            "Narjis Jabbari / Khadija Tnana",
            "Hajar Moussa / Chadine Hayoun",
          ],
          note: null,
        },
        {
          time: "17h30",
          title: "Cérémonie d'ouverture",
          subtitle: null,
          moderator: {
            label: "Animation",
            text: "**Fatima Zahra Sghier**",
          },
          sectionLabel: null,
          participants: [
            "Mot d'ouverture de la présidente de la Fondation",
            "Hommage à la réalisatrice **Farida Belyazid**",
            "Témoignage par le poète/journaliste **Abdellatif Ben Yahya**",
          ],
          note: null,
        },
        {
          time: "18h30",
          title: "Rencontre",
          subtitle:
            "Les univers créatifs de femmes artistes issues de différents domaines",
          moderator: {
            label: "Animation",
            text: "**Fatima Zahra Sghier**",
          },
          sectionLabel: "Intervenantes :",
          participants: [
            "**Rabia Rihane** : l'écriture",
            "**Mariam Tamsamani** : la poésie haïku",
            "**Naïma Zitan** : la mise en scène théâtrale",
            "**Touriya Al-Hadraoui** : le chant du Malhoun",
            "**Dania Achour** : la réalisation cinématographique",
          ],
          note: null,
        },
        {
          time: "19h30",
          title: "Lectures poétiques",
          subtitle: null,
          moderator: {
            label: "Animation",
            text: "**Halima El Mourabit**",
          },
          sectionLabel: "Avec :",
          participants: [
            "Aïcha Basri",
            "Fatima Zahra Bennis",
            "Mariam Tamsamani",
            "Mariam Kroudi",
          ],
          note: null,
        },
        {
          time: "20h30",
          title: "Soirée artistique",
          subtitle: "Soirée artistique consacrée aux poèmes du Malhoun",
          moderator: null,
          sectionLabel: null,
          participants: [],
          note: "Avec **Touraya Al-Hadraoui**",
        },
      ],
      ar: [
        {
          time: "16:00",
          title: "افتتاح معرض تشكيلي",
          subtitle: null,
          moderator: {
            label: "تقديم",
            text: "فاطمة الزهراء الصغير و لاليدا بيسماح",
          },
          sectionLabel: "بمشاركة الفنانات:",
          participants: [
            "أمينة رزقي",
            "ريم العباسي",
            "تشدين بيون",
            "خديجة طنانة",
            "نرجس الجيلالي",
            "هاجر موسى",
          ],
          note: null,
        },
        {
          time: "17:30",
          title: "حفل الافتتاح",
          subtitle: null,
          moderator: {
            label: "تسيير",
            text: "فاطمة الزهراء الصغير",
          },
          sectionLabel: null,
          participants: [
            "الكلمة الافتتاحية لرئيسة المؤسسة: الفنانة خديجة طنانة",
            "تكريم الفنانة المخرجة: فريدة بليزيد",
            "شهادة في حقها للشاعر والصحافي عبد اللطيف بن يحيي",
          ],
          note: null,
        },
        {
          time: "18:30",
          title: "جلسة البوح",
          subtitle: "عالم الإبداع لفنانات من حقول إبداعية متنوعة",
          moderator: {
            label: "تسيير",
            text: "حفيظة هيذور",
          },
          sectionLabel: null,
          participants: [
            "الكاتبة: ربيعة ريحان",
            "مريم التسماني",
            "نعيمة بطلان",
            "ثريا الخضراوي",
            "دانية عاشور",
            "التشكيل: السعدية الماكي",
            "الإخراج المسرحي: طرب المامون",
            "الإخراج السينمائي",
          ],
          note: null,
        },
        {
          time: "19:30",
          title: "قراءات شعرية",
          subtitle: null,
          moderator: {
            label: "تسيير",
            text: "حليمة المرابط",
          },
          sectionLabel: "للشاعرات:",
          participants: [
            "عائشة البصري",
            "فاطمة الزهراء بنيس",
            "مريم التسماني",
            "مريم كلودي",
          ],
          note: null,
        },
        {
          time: "20:30",
          title: "عرض فيلم",
          subtitle: null,
          moderator: null,
          sectionLabel: null,
          participants: [
            "فيلم للمخرجة فريدة بليزيد",
            "Les femmes dans la musique Amazighe",
          ],
          note: null,
        },
        {
          time: "22:00",
          title: "سهرة فنية",
          subtitle: "سهرة فنية لقصائد الملحون مع الفنانة ثريا الخضراوي",
          moderator: null,
          sectionLabel: null,
          participants: [],
          note: null,
        },
      ],
    },
  },

  {
    id: "jour-2",
    label: { fr: "Deuxième jour : 27 juin", ar: "اليوم الثاني: 27 يونيو" },
    shortDate: { fr: "27 juin", ar: "27 يونيو" },
    events: {
      fr: [
        {
          time: "11h00",
          title: "Conférence culturelle",
          subtitle: "Vivons-nous la fin du livre ou ses transformations ?",
          moderator: {
            label: "Animation",
            text: "**Youssef Saâdoun**",
          },
          sectionLabel: "Avec la participation de :",
          participants: [
            "Souad Meskine",
            "Soumaya Ahmed El Mouden",
            "Imad Bellatar",
            "Abdelkrim Lachkar",
          ],
          note: null,
        },
        {
          time: "16h00",
          title: "« Elles écrivent... Écoutons-les »",
          subtitle: null,
          moderator: {
            label: "Animation",
            text: "**Mustapha Stitou**",
          },
          sectionLabel: null,
          participants: [
            "**Aïcha Basri** : lecture et présentation par **Mohamed Al-Annaz**",
            "**Rabia Rihane** : lecture et présentation par **Hassan El Yamlahi**",
            "Séance de dédicace des ouvrages des écrivaines",
          ],
          note: null,
        },
        {
          time: "18h00",
          title: "L'écriture comme moteur d'accès au monde de la création",
          subtitle: null,
          moderator: {
            label: "Animation",
            text: "**Youssef Saâdoun**",
          },
          sectionLabel: "Intervenantes :",
          participants: [
            "**Nadia Sabri** (chercheuse)",
            "**Dounia Belkacem**",
            "**Maria Khoussi Benito**",
            "**Rouyi** – présentation par **Fatima Zahra Sghir**",
            "**Dalida BenSafaj** (réalisatrice)",
            "**Dania Achour** (réalisatrice)",
          ],
          note: null,
        },
        {
          time: "21h00",
          title: "Cérémonie de clôture",
          subtitle: null,
          moderator: null,
          sectionLabel: null,
          participants: [],
          note: "Animée par l'artiste **Imane Nouba**",
        },
      ],
      ar: [
        {
          time: "10:00",
          title: "ندوة ثقافية",
          subtitle: "هل تعيش نهاية الكتاب أم تحولاته؟",
          moderator: {
            label: "تسيير",
            text: "يوسف سعدون",
          },
          sectionLabel: "بمشاركة الأستاذات والأساتذة:",
          participants: [
            "سعيدة مسكين",
            "سمية أحمد المومن",
            "عماد العطار",
            "عبد الكريم الشكر",
          ],
          note: null,
        },
        {
          time: "17:30",
          title: "لقاء أدبي",
          subtitle: "هن يكتبن... فلنصت لهن",
          moderator: {
            label: "تسيير",
            text: "مصطفى الستتي",
          },
          sectionLabel: null,
          participants: [
            "الكاتبة عائشة البصري: قراءة وتقديم الأستاذ محمد العزاز",
            "الكاتبة ربيعة ريحان: قراءة وتقديم الأستاذ حسن البلمدحي",
          ],
          note: null,
        },
        {
          time: "20:00",
          title: 'لقاء: "الكتابة كفاعل للحاق بركب الإبداع"',
          subtitle: null,
          moderator: {
            label: "تسيير",
            text: "يوسف سعدون",
          },
          sectionLabel: "للكاتبات والمخرجات:",
          participants: [
            "نادية صبري",
            "دنيا بنقاسم",
            "مونية موسى بنبطو / خديجة طنانة",
            "أكد الموساوي",
            "لاليدا بيسماح",
            "داليا عاشور",
          ],
          note: null,
        },
        {
          time: "22:00",
          title: "حفل اختتام",
          subtitle: null,
          moderator: null,
          sectionLabel: null,
          participants: [
            "سهرة فنية تحييها الفنانة إيمان نويا",
          ],
          note: null,
        },
      ],
    },
  },
];

export const festivalMeta = {
  title: "Programme : Festival culturel et artistique",
  subtitle: "1ère édition : femmes et les mondes de la création",
  dates: "26 et 27 juin 2026",
  venue: "Jbel Zemzem, face a Marina Smir",
  city: "Tétouan, Maroc",
  organizer: "Fondation Khadija Tnana pour la culture et les arts",
  website: "f-tnana.ma",
};
