name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git config --global --add safe.directory /home/debian/khadijaTN
            chown -R debian:debian /home/debian/khadijaTN
            find /home/debian/khadijaTN -name "*.timestamp-*" -delete
            sudo -u debian git -C /home/debian/khadijaTN pull
            sudo -u debian npm --prefix /home/debian/khadijaTN run build
            rm -rf /var/www/k-tnana.com/*
            cp -r /home/debian/khadijaTN/dist/* /var/www/k-tnana.com/
